%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name ts-loader

Name: %{?scl_prefix}nodejs-ts-loader
Version: 9.5.2
Release: 1%{?dist}
Summary: TypeScript loader for webpack
License: MIT
Group: Development/Libraries
URL: https://github.com/TypeStrong/ts-loader
Source0: https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz
Source1: https://registry.npmjs.org/braces/-/braces-3.0.3.tgz
Source2: https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz
Source3: https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz
Source4: https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz
Source5: https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-5.18.4.tgz
Source6: https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz
Source7: https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz
Source8: https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz
Source9: https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz
Source10: https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz
Source11: https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz
Source12: https://registry.npmjs.org/semver/-/semver-7.7.3.tgz
Source13: https://registry.npmjs.org/source-map/-/source-map-0.7.6.tgz
Source14: https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz
Source15: https://registry.npmjs.org/tapable/-/tapable-2.3.0.tgz
Source16: https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz
Source17: https://registry.npmjs.org/ts-loader/-/ts-loader-9.5.2.tgz
Source18: nodejs-ts-loader-%{version}-registry.npmjs.org.tgz
BuildRequires: %{?scl_prefix_nodejs}npm
%if 0%{!?scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}
Provides: bundled(npm(ansi-styles)) = 4.3.0
Provides: bundled(npm(braces)) = 3.0.3
Provides: bundled(npm(chalk)) = 4.1.2
Provides: bundled(npm(color-convert)) = 2.0.1
Provides: bundled(npm(color-name)) = 1.1.4
Provides: bundled(npm(enhanced-resolve)) = 5.18.4
Provides: bundled(npm(fill-range)) = 7.1.1
Provides: bundled(npm(graceful-fs)) = 4.2.11
Provides: bundled(npm(has-flag)) = 4.0.0
Provides: bundled(npm(is-number)) = 7.0.0
Provides: bundled(npm(micromatch)) = 4.0.8
Provides: bundled(npm(picomatch)) = 2.3.1
Provides: bundled(npm(semver)) = 7.7.3
Provides: bundled(npm(source-map)) = 0.7.6
Provides: bundled(npm(supports-color)) = 7.2.0
Provides: bundled(npm(tapable)) = 2.3.0
Provides: bundled(npm(to-regex-range)) = 5.0.1
Provides: bundled(npm(ts-loader)) = 9.5.2
AutoReq: no
AutoProv: no

%if 0%{?scl:1}
%define npm_cache_dir npm_cache
%else
%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}
%endif

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
%{?scl:scl enable %{?scl_nodejs} - << \end_of_scl}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done
%{?scl:end_of_scl}

%setup -T -q -a 18 -D -n %{npm_cache_dir}

%build
%{?scl:scl enable %{?scl_nodejs} - << \end_of_scl}
npm install --legacy-peer-deps --cache-min Infinity --cache %{?scl:../}%{npm_cache_dir} --no-shrinkwrap --no-optional --global-style true %{npm_name}@%{version}
%{?scl:end_of_scl}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/renovate.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/CHANGELOG.md
%doc node_modules/%{npm_name}/README.md
%doc node_modules/%{npm_name}/REFERENCES.md
%doc node_modules/%{npm_name}/SECURITY.md

%changelog
* Mon Dec 15 2025 Nadja Heitmann <nadjah@atix.de> 9.5.2-1
- Add nodejs-ts-loader generated by npm2rpm using the bundle strategy

